services:
  postgres:
    image: postgres:16
    ports:
      - "5499:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: index_practice
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
